### ISSUE TITLE
I hope to provide a graphical interface

### ISSUE THREAD

**Issue by baguotao233** [515621078/GoogleTrans20#2]
Dear author, hello, I feel very difficult to use your software in the process of using it, because there is no GUI, no detailed documentation, and it is not very convenient to use. I hope the author can support GUI，And make a detailed use document.

**Comment by NnWinter** [comment]
Hi, thanks for your suggestion
Here's what I think: 

This project is currently too simple for a GUI. It's coded in C#, unlike Java or Python, to support cross platform, I think that Console IO would be my first choice. And I'll try to rebuild a cross platform version with .Net 6.

You're right about the document issue. Yes, this project doesn't have a good readme document. I'll try to do something about it :)
The user guide was published on bilibili when I creat this project at the link below. If you speak Chinese, you could check it first while I add some new features. Cheers 🍻

感谢你的反馈，我是这么想的：

这个程序挺简单的，用纯控制台会更方便支持多平台。
毕竟是 C# 写的，不像Java或Python，我也打算换成 .Net 6 来支持多平台，所以目前可能还是会考虑控制台模式为主。

确实，没有写好说明文档。当时是主要发布在哔哩哔哩上边，我接下来会试着加上说明 并加入一些新功能。
在此期间你可以先用下边的链接前往bilibili查看使用说明。
(゜v゜)つロ干杯~

【【工具】谷歌翻译20次工具-哔哩哔哩】 https://b23.tv/OVwJAPl

**Comment by launchpad001** [comment]
> 

事实上GUI完全没必要，控制台大部分人应该也能很快上手

如果真的要做GUI，单独做一个程序来实现就可以了（我看到过一个原神加密视频解密的软件，那个就是C#的核心+Python的GUI）

**Comment by NnWinter** [comment]
> > 
> 
> 事实上GUI完全没必要，控制台大部分人应该也能很快上手
> 
> 如果真的要做GUI，单独做一个程序来实现就可以了（我看到过一个原神加密视频解密的软件，那个就是C#的核心+Python的GUI）

嗯，C# 的话现在也不是很需要用 Python 来实现 GUI，全平台可以用新的 MAUI 来做 (好像是这两年才有的)
我已经开始用 .NET6 重写了，争取搞个全平台支持

**Comment by baguotao233** [comment]
I think this software is very difficult to use. I strongly recommend adding a document to make it easy for others to use (I think it is too difficult to use for the first time)

我觉得这个软件很难使用，我强烈建议增加一个文档，方便其他人使用（我第一次用起来觉得太难用了）

**Comment by baguotao233** [comment]
![image](https://user-images.githubusercontent.com/112544116/215323522-e799e286-e4e9-488d-9cbf-47cfbf8edd5e.png)

You see, this software is really difficult to use. I often write wrong parameters and then report a lot of errors

你看，这个软件确实难以使用，我经常写错参数，然后一堆报错

@rdp-studio

**Comment by NnWinter** [comment]
> I think this software is very difficult to use. I strongly recommend adding a document to make it easy for others to use (I think it is too difficult to use for the first time)
> 
> 我觉得这个软件很难使用，我强烈建议增加一个文档，方便其他人使用（我第一次用起来觉得太难用了）

在写了在写了，你可以看一下另一个 Branch，就是 v2，我用 .Net6 重写了一个全平台的版本
交互模式也进行了修改，变成了有菜单，有选项的模式

再就是添加了对有道API的支持，因为国内翻墙成本变大了，GoogleAPI 有时候不太行

新版预览：
![image](https://user-images.githubusercontent.com/39520908/215323817-3dd4e7ca-d8b3-4dd7-87e2-62f3ff785591.png)

这样的交互模式应该会比之前好一点？

**Comment by baguotao233** [comment]
Yes, the UI design is very good this time, so that more users can understand it easily
I wish you a very smooth development process

是的，这次的UI设计非常不错，这样就让更多用户简单易懂了
祝你在开发过程中非常顺利
@515621078

**Comment by NnWinter** [comment]
@baguotao233 更新新版了喔，如果 UI 这一块问题不大的话，我晚点就把这个 Close 了喔？(¦3[▓▓]

**Comment by NnWinter** [comment]
应该是没什么问题了

**Comment by baguotao233** [comment]
非常感谢作者的积极处理，希望作者（UP主）的程序更好用
